apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: do-cloud-install-task
spec:
  params:
      - name: doauth
        type: string
      - name: file2
        type: string
      - name: uuid
        type: string
  steps:
    - name: login-and-deploy-function
      image: alpine:3.13.0
      script: |
        #!/usr/bin/env sh 
        apk add wget
        wget https://github.com/digitalocean/doctl/releases/download/v1.54.0/doctl-1.54.0-linux-amd64.tar.gz
        tar xf doctl-1.54.0-linux-amd64.tar.gz
        mv doctl /usr/local/bin

        # yum install zip -y
        # yum install unzip -y
        # yum install wget -y

        # mkdir -p ./application
        # wget $(params.file2) -O goapp.zip
        # unzip ./goapp.zip -d ./application
        # rm goapp.zip
        # echo $(params.uuid)
        # cd application/microservice-go-demo-main
        # ls -la
        pwd
        doctl auth init -t $(params.doauth)
        doctl account get
        