apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener
spec:
  triggers:
    - binding:
        name: event-trigger-binding
      template:
        name: event-trigger-template